### ISSUE TITLE
LL: Switch from Uniswap v2 to Sushiswap v2

### ISSUE THREAD

**Issue by udosson** [kumodao/borrowprot#109]
## Overview
As a user of the lending protocol, I want to be able to swap KUSD via Sushiswap on Polygon.

## Background
Liquity uses Uniswap v2 in its deployment to create a liquidity pool (LP). On Polygon, however, Uniswap is not deployed but Sushiswap is. We stick to v2 for now and will evaluate v2 vs. v3 at a later point in time.

## Intended Outcome
Replaced Uniswap with Sushiswap v2.

## Tasks
- [x] Change smart contract addresses
- [x] Verify if tests need to be updated
- [x] Test Sushiswap LP live on Mumbai

**Comment by udosson** [comment]
No need to change anything but the smart contract addresses. Anything else we need to consider @arthurka-o ?
