### ISSUE TITLE
Switch from LUSD to KUSD

### ISSUE THREAD

**Issue by udosson** [kumodao/borrowprot#34]
## Overview
Kumo enables borrowing a stablecoin against tokenized carbon credits. The stablecoin is called `KUSD` which stands for Kumo USD. 

## Intended Outcome
`KUSD` is the ERC20 token used as stablecoin in the system. All tests have to be adjusted to run with `KUSD` rather than `LUSD`.

## Tasks
- [x] #35 
- [x] #37 
- [x] Integrate `KUSD` in `./packages/lib-base`
- [x] Integrate `KUSD` in `./packages/lib-ethers`
- [x] Integrate `KUSD` in `./packages/lib-subgraph`
- [x] Integrate `KUSD` in `./packages/subgraph`

**Comment by udosson** [comment]
@wollooo Let's use this branch for development https://github.com/kumodao/borrowprot/tree/34-switch-from-lusd-to-kusd

**Comment by wollooo** [comment]
done at [#66](https://github.com/kumodao/borrowprot/pull/66)
