### ISSUE TITLE
Switch from LQTY to KUMO Token

### ISSUE THREAD

**Issue by udosson** [kumodao/borrowprot#40]
## Overview
Kumo is a DAO and will be decentrally governed. The on-chain governance requires the governance token called `KUMO`. Holders of `KUMO` will be able to participate in the governance of the DAO and also be able to stake the token.

## Intended Outcome
`KUMO` is the ERC20 governance token of KumoDAO and replaces the `LQTY` token from Liquity. All smart contracts and tests have to be adjusted to use `KUMO`.

## Tasks
- [x] #42 
- [x] #43 
- [x] #44 
- [x] Integrate `KUMO` in `./packages/lib-base`
- [x] Integrate `KUMO` in `./packages/lib-ethers`
- [x] Integrate `KUMO` in `./packages/lib-subgraph`
- [x] Integrate `KUMO` in `./packages/subgraph`

**Comment by wollooo** [comment]
done at [#66](https://github.com/kumodao/borrowprot/pull/66)
